---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./helmrelease.yaml
  - ./secret.sops.yaml
commonLabels:
  app.kubernetes.io/name: dsmr-reader
  app.kubernetes.io/instance: dsmr-reader
