apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: dsmr-reader-secret
    namespace: default
stringData:
        POSTGRES_HOST: &database_host postgres-v15-rw.database.svc.cluster.local
        POSTGRES_SUPER_PASS: "{{ .cnpg_postgres_superuser_password }}"
        POSTGRES_USER: haasie
        POSTGRES_PASS: ryuZfRKkFLhHhTpqz2Xn
        POSTGRES_DB: &database_name dsmr-reader

        DJANGO_DATABASE_HOST: *database_host
        DJANGO_DATABASE_USER: "{{ .dsmr_reader_postgres_username }}"
        DJANGO_DATABASE_PASSWORD: "{{ .dsmr_reader_postgres_password }}"
        DJANGO_DATABASE_PORT: "5432"
        DJANGO_DATABASE_NAME: *database_name
        DSMRREADER_ADMIN_USER: "{{ .dsmr_reader_username }}"
        DSMRREADER_ADMIN_PASSWORD: "{{ .dsmr_reader_password }}"
